image: docker:20.10.12
services:
  - docker:dind

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
  - release
  - deploy

release:
  stage: release
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE:$CI_COMMIT_REF_NAME .
  only:
    - /^release\/.*$/
    - tags

deploy:
  stage: deploy
  script:
    - docker stop blog-backend
    - docker rm blog-backend
    - docker run -d --name game-server -p 13000:13000 $CONTAINER_RELEASE_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - /^release\/.*$/
    - tags