[core]
mod-path = "D:/Project/project-craft-net/CoreMod/bin/Debug"
max-player = 20
localization-path = "D:/Project/project-craft-net/ProjectCraftNet/resources/localization"
log-level = "debug"

[network-tcp]
host = "127.0.0.1"
port = 13000